### ISSUE TITLE
Title screen logos

### ISSUE THREAD

**Issue by Rhernandez513** [Rhernandez513/Hangman-Comp-170-Final-Proj#11]
@akielkopf

Get the title screens to have better presentation 

Splitting it into 2 screens with 2 button presses seems the most straight forward way. 

This may require making them 2 files with 2 loops. 

If anything this is a good opportunity to take the loop that produces an output from the text file and make it a as a function.

**Comment by akielkopf** [comment]
done. and i just pushed the changes to my branch Andy Develop1
